# Generated by Django 5.2.5 on 2025-08-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='predicted_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
